model_name: pebble
base_model: openlm-research/open_llama_3b_v2
model_family: llama 
model_context_window: 2048  # if unspecified will use tokenizer.model_max_length
data:
  type: vicuna
  dataset: ../drive/MyDrive/dataset
  user_header: "### Instruction:\n"
  response_header: "### Response:\n"
lora:
  r: 16
  lora_alpha: 64
  target_modules:  # modules for which to train lora adapters
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  lora_dropout: 0.10
  bias: none
  task_type: CAUSAL_LM
trainer:
  batch_size: 1
  gradient_accumulation_steps: 1
  warmup_steps: 100
  num_train_epochs: 1
  learning_rate: 0.0002
  logging_steps: 20
trainer_output_dir: trainer_outputs/
model_output_dir: models/  # model saved in {model_output_dir}/{model_name}
